// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Auth: typeof import('./../src/components/Auth/index.vue')['default']
    AuthAll: typeof import('./../src/components/AuthAll/index.vue')['default']
    BatchActionBar: typeof import('./../src/components/BatchActionBar/index.vue')['default']
    CascaderArea: typeof import('./../src/components/CascaderArea/index.vue')['default']
    Copyright: typeof import('./../src/components/Copyright/index.vue')['default']
    Editor: typeof import('./../src/components/Editor/index.vue')['default']
    ElAlert: typeof import('element-plus/es')['ElAlert']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElBacktop: typeof import('element-plus/es')['ElBacktop']
    ElBreadcrumb: typeof import('element-plus/es')['ElBreadcrumb']
    ElBreadcrumbItem: typeof import('element-plus/es')['ElBreadcrumbItem']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElLink: typeof import('element-plus/es')['ElLink']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElRadioButton: typeof import('element-plus/es')['ElRadioButton']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    FileUpload: typeof import('./../src/components/FileUpload/index.vue')['default']
    FixedActionBar: typeof import('./../src/components/FixedActionBar/index.vue')['default']
    Footer: typeof import('./../src/components/footer/index.vue')['default']
    Header: typeof import('./../src/components/Header/index.vue')['default']
    ImagePreview: typeof import('./../src/components/ImagePreview/index.vue')['default']
    ImagesUpload: typeof import('./../src/components/ImagesUpload/index.vue')['default']
    ImageUpload: typeof import('./../src/components/ImageUpload/index.vue')['default']
    PageHeader: typeof import('./../src/components/PageHeader/index.vue')['default']
    PageMain: typeof import('./../src/components/PageMain/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchBar: typeof import('./../src/components/SearchBar/index.vue')['default']
    SvgIcon: typeof import('./../src/components/SvgIcon/index.vue')['default']
    Trend: typeof import('./../src/components/Trend/index.vue')['default']
  }
}
